package map;

public enum LogicPixel {
    HERO,
    SWORDSMAN,
    ATTACK,
    LIGHT_1, LIGHT_2, LIGHT_3,
    DARKNESS_1, DARKNESS_2, DARKNESS_3, DARKNESS_FULL,
    SAND_WALL, SAND_BACKGROUND_EMPTY, SAND_BACKGROUND_1, SAND_BACKGROUND_2, SAND_BACKGROUND_3,
    NIGHT_TREE_1, NIGHT_TREE_2, GRASS_BACKGROUND_EMPTY, GRASS_BACKGROUND_1, GRASS_BACKGROUND_2,
    WATER_WALL, WATER_BACKGROUND_EMPTY, WATER_BACKGROUND_1, WATER_BACKGROUND_2,
    DUNGEON_WALL, DUNGEON_BACKGROUND_EMPTY, DUNGEON_BACKGROUND_1, DUNGEON_BACKGROUND_2
}

